apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
data:
  cluster-name: "${cluster_name}"
  node-count: "${node_count}"
  instance-type: "${instance_type}"
  region: "us-west-2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: ${node_count}
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: CLUSTER_NAME
          value: "${cluster_name}"
        - name: NODE_TYPE
          value: "${instance_type}"

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
