apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
data:
  cluster-name: "bridgephase-prod"
  node-count: "5"
  instance-type: "t3.xlarge"
  region: "us-west-2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: CLUSTER_NAME
          value: "bridgephase-prod"
        - name: NODE_TYPE
          value: "t3.xlarge"

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
